# $FreeBSD: releng/12.0/sys/modules/xl/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/xl

KMOD=	if_xl
SRCS=	bus_if.h device_if.h if_xl.c miibus_if.h miidevs.h pci_if.h xlphy.c

.include <bsd.kmod.mk>
