# $FreeBSD: releng/12.0/tests/sys/cddl/zfs/Makefile 329867 2018-02-23 16:31:00Z asomers $

.include <src.opts.mk>

TESTSDIR=	${TESTSBASE}/sys/cddl/zfs

TESTS_SUBDIRS+=	tests include

SUBDIR+=		bin

.include <bsd.test.mk>
