# $FreeBSD: releng/12.0/usr.sbin/ancontrol/Makefile 314659 2017-03-04 11:38:03Z ngie $

PROG=	ancontrol
MAN=	ancontrol.8

WARNS?=	3
CFLAGS+= -DANCACHE -I${SRCTOP}/sys

LIBADD=	md

.include <bsd.prog.mk>
