# $FreeBSD: releng/12.0/lib/libpmcstat/Makefile 334244 2018-05-26 19:29:19Z mmacy $
PACKAGE=lib${LIB}
LIB=	pmcstat
INTERNALLIB=

SRCS=	\
	libpmcstat_event.c	\
	libpmcstat_image.c	\
	libpmcstat_logging.c	\
	libpmcstat_process.c	\
	libpmcstat_string.c	\
	libpmcstat_symbol.c
INCS=	libpmcstat.h

.include <bsd.lib.mk>
