# $FreeBSD: releng/12.0/usr.sbin/zonectl/Makefile 314461 2017-03-01 04:19:04Z ngie $

PROG=	zonectl
SRCS=	zonectl.c
SDIR=	${SRCTOP}/sys
LIBADD= cam sbuf util
MAN=	zonectl.8
CFLAGS+=-g -O0

.include <bsd.prog.mk>
