# $FreeBSD: releng/12.0/usr.bin/clang/llvm-dwarfdump/Makefile 327952 2018-01-14 00:08:34Z dim $

PROG_CXX=	llvm-dwarfdump

SRCDIR=		tools/llvm-dwarfdump
SRCS+=		Statistics.cpp
SRCS+=		llvm-dwarfdump.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
