# $FreeBSD: releng/12.0/usr.bin/clang/clang-format/Makefile 309124 2016-11-24 22:54:55Z dim $

PROG_CXX=	clang-format
MAN=

SRCDIR=		tools/clang/tools/clang-format
SRCS+=		ClangFormat.cpp

.include "../clang.prog.mk"
