#       $NetBSD: Makefile,v 1.3 2009/04/14 22:15:26 lukem Exp $
# $FreeBSD: releng/12.0/usr.bin/seq/Makefile 330086 2018-02-27 22:01:40Z cem $

.include <src.opts.mk>

PROG=	seq

LIBADD=	m

HAS_TESTS=
SUBDIR.${MK_TESTS}+=	tests

.include <bsd.prog.mk>
