# $FreeBSD: releng/12.0/sys/modules/geom/geom_virstor/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/geom/virstor

KMOD=	geom_virstor
SRCS=	g_virstor.c g_virstor_md.c binstream.c

.include <bsd.kmod.mk>
