# $FreeBSD: releng/12.0/sys/modules/ntb/if_ntb/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:  ${SRCTOP}/sys/dev/ntb/if_ntb

KMOD    = if_ntb
SRCS    = if_ntb.c
SRCS += device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
