#	@(#)Makefile	5.4 (Berkeley) 6/5/91
# $FreeBSD: releng/12.0/sbin/etherswitchcfg/Makefile 314656 2017-03-04 11:33:01Z ngie $

PACKAGE=runtime
PROG=	etherswitchcfg
MAN=	etherswitchcfg.8
SRCS=	etherswitchcfg.c ifmedia.c
CFLAGS+= -I${SRCTOP}/sys

.include <bsd.prog.mk>
