# $FreeBSD: releng/12.0/usr.bin/mkcsmapper/Makefile 315170 2017-03-12 18:58:44Z imp $

.PATH: ${SRCTOP}/lib/libc/iconv

PROG=	mkcsmapper
LDFLAGS+= -L${SRCTOP}/lib/libc

NO_WMISSING_VARIABLE_DECLARATIONS=

.include "${.CURDIR}/Makefile.inc"
.include <bsd.prog.mk>
