# $FreeBSD: releng/12.0/stand/libsa32/Makefile 325694 2017-11-10 23:54:58Z imp $

DO32=1

.include <bsd.init.mk>

LIB=sa32
LIBSA_CPUARCH=${MACHINE_CPUARCH:C/amd64/i386/}

.PATH:	${SASRC}
.include "${SASRC}/Makefile"
