#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: releng/12.0/usr.bin/primes/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG=	primes
SRCS=	pattern.c pr_tbl.c primes.c spsp.c
MAN=
LIBADD=	m

.include <bsd.prog.mk>
