# $FreeBSD: releng/12.0/share/examples/smbfs/print/Makefile 314652 2017-03-04 11:26:40Z ngie $

PACKAGE=examples
FILESDIR= ${SHAREDIR}/examples/smbfs/print
FILES=	lj6l ljspool printcap.sample tolj

.PATH: ${SRCTOP}/contrib/smbfs/examples/print

.include <bsd.prog.mk>
