# $FreeBSD: releng/12.0/sys/modules/s3/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/fb

KMOD=	s3
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h \
	s3_pci.c

.include <bsd.kmod.mk>
