# $FreeBSD: releng/12.0/usr.bin/clang/llvm-diff/Makefile 327952 2018-01-14 00:08:34Z dim $

PROG_CXX=	llvm-diff

SRCDIR=		tools/llvm-diff
SRCS+=		DiffConsumer.cpp
SRCS+=		DiffLog.cpp
SRCS+=		DifferenceEngine.cpp
SRCS+=		llvm-diff.cpp

.include "../llvm.prog.mk"
