# $FreeBSD: releng/12.0/sys/modules/ipw/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/ipw

KMOD    = if_ipw
SRCS    = if_ipw.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
