# $FreeBSD: releng/12.0/sys/modules/aic7xxx/aicasm/Makefile 314651 2017-03-04 10:10:17Z ngie $

MAKESRCPATH=	${SRCTOP}/sys/dev/aic7xxx/aicasm

install:

.include "${SRCTOP}/sys/dev/aic7xxx/aicasm/Makefile"

build-tools: ${PROG}
