# $FreeBSD: releng/12.0/sys/modules/dtb/mv/Makefile 318068 2017-05-09 18:12:05Z loos $
# All the dts files for Marvell systems we support.
DTS=	\
	armada-388-clearfog.dts \
	armada-388-gp.dts

.include <bsd.dtb.mk>
