# $FreeBSD: releng/12.0/sys/modules/amd_ecc_inject/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/amd_ecc_inject

KMOD=	amd_ecc_inject
SRCS=	ecc_inject.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
