# $FreeBSD: releng/12.0/usr.bin/diff3/tests/Makefile 318888 2017-05-25 17:45:50Z bapt $

PACKAGE=	tests

ATF_TESTS_SH=	diff3_test

${PACKAGE}FILES+=	\
	1.txt \
	2.txt \
	3.txt \
	1.out \
	2.out \
	3.out \
	4.out \
	5.out \
	6.out \
	7.out \
	8.out \
	9.out

.include <bsd.test.mk>
