#	$FreeBSD: releng/12.0/sbin/ipf/ipresend/Makefile 314656 2017-03-04 11:33:01Z ngie $

PACKAGE=	ipf
PROG=		ipresend
SRCS=		ipresend.c ip.c resend.c sbpf.c sock.c 44arp.c
MAN=		ipresend.1

.PATH:		${SRCTOP}/contrib/ipfilter/ipsend

.include <bsd.prog.mk>
