# $FreeBSD: releng/12.0/sys/modules/amr/amr_cam/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/amr

KMOD=	amr_cam
SRCS=	amr_cam.c device_if.h bus_if.h
SRCS+=	opt_cam.h opt_scsi.h

.include <bsd.kmod.mk>
