# $FreeBSD: releng/12.0/sys/modules/dtb/am335x/Makefile 337877 2018-08-15 21:47:03Z manu $
# All the dts files for am335x systems we support.
DTS=	\
	am335x-bone.dts \
	am335x-boneblack.dts \
	am335x-boneblack-wireless.dts \
	am335x-bonegreen.dts \
	am335x-bonegreen-wireless.dts \
	am335x-boneblue.dts \
	am335x-pocketbeagle.dts \
	ufw.dts

.include <bsd.dtb.mk>
