# $FreeBSD: releng/12.0/cddl/usr.bin/zlook/Makefile 314654 2017-03-04 11:30:04Z ngie $

.PATH: ${SRCTOP}/cddl/contrib/opensolaris/cmd/zlook

PROG=	zlook
MAN=

WARNS?=	0
CFLAGS+= -I${SRCTOP}/sys/cddl/compat/opensolaris
CFLAGS+= -I${SRCTOP}/sys/cddl/contrib/opensolaris/uts/common

.include <bsd.prog.mk>
