# $FreeBSD: releng/12.0/sys/modules/mse/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/mse

KMOD=	mse
SRCS=	mse.c mse_isa.c device_if.h bus_if.h isa_if.h

.include <bsd.kmod.mk>
