#	$FreeBSD: releng/12.0/libexec/tftp-proxy/Makefile 314653 2017-03-04 11:28:03Z ngie $

.PATH:	${SRCTOP}/contrib/pf/tftp-proxy

PROG=	tftp-proxy
SRCS=	tftp-proxy.c filter.c
MAN=	tftp-proxy.8

WARNS?=	3

.include <bsd.prog.mk>
