# $FreeBSD: releng/12.0/usr.sbin/pnpinfo/Makefile 314659 2017-03-04 11:38:03Z ngie $

.PATH: ${SRCTOP}/contrib/pnpinfo

PROG=	pnpinfo
MAN=	pnpinfo.8

CFLAGS+= -I${SRCTOP}/sys

WARNS?=	2

.include <bsd.prog.mk>
