# $FreeBSD: releng/12.0/usr.bin/less/Makefile.common 315170 2017-03-12 18:58:44Z imp $

LSDIR=	${SRCTOP}/contrib/less
.PATH:	${LSDIR}

CFLAGS+=-I${SRCTOP}/usr.bin/less -I${LSDIR}
WARNS?=	1

.SUFFIXES: .nro .1

.nro.1:
	cat ${.IMPSRC} > ${.TARGET}
