# $FreeBSD: releng/12.0/cddl/Makefile 321912 2017-08-02 08:35:51Z ngie $

.include <src.opts.mk>

SUBDIR=	lib .WAIT \
	sbin usr.bin usr.sbin

SUBDIR.${MK_TESTS}+= tests

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
