# $FreeBSD: releng/12.0/sys/modules/i2c/iic/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:		${SRCTOP}/sys/dev/iicbus
KMOD		= iic
SRCS		= device_if.h bus_if.h iicbus_if.h \
		  iic.c

.include <bsd.kmod.mk>
