#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/12.0/usr.sbin/lpr/lptest/Makefile 314475 2017-03-01 05:14:45Z ngie $

PROG=	lptest

CFLAGS+= -I${.CURDIR:H}/common_source

.include <bsd.prog.mk>
