# $FreeBSD: releng/12.0/lib/libveriexec/Makefile 335401 2018-06-20 00:55:18Z stevek $

.include <bsd.own.mk>

LIB=		veriexec
MAN=		veriexec.3
INCS=		libveriexec.h

WARNS?=		2

SRCS=		veriexec_check.c

.include <bsd.lib.mk>

