# $FreeBSD: releng/12.0/sys/modules/asmc/Makefile 334170 2018-05-24 17:06:00Z cem $

.PATH: ${SRCTOP}/sys/dev/asmc

KMOD=	asmc
SRCS=	asmc.c opt_acpi.h acpi_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
