#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/12.0/usr.bin/locate/bigram/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=	locate.bigram
MAN=
BINDIR=	${LIBEXECDIR}
CFLAGS+= -I${.CURDIR}/../locate

.include <bsd.prog.mk>
