# $FreeBSD: releng/12.0/sys/modules/ntb/ntb/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:  ${SRCTOP}/sys/dev/ntb

KMOD    = ntb
SRCS    = ntb.c ntb_if.c
SRCS += device_if.h bus_if.h ntb_if.h

.include <bsd.kmod.mk>
