# $FreeBSD: releng/12.0/usr.bin/units/Makefile 322515 2017-08-14 19:21:37Z ngie $

.include <src.opts.mk>

PROG=	units
FILES=	definitions.units
FILESDIR=	${SHAREDIR}/misc

LIBADD=	edit

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
