# $FreeBSD: releng/12.0/usr.bin/lesskey/Makefile 315170 2017-03-12 18:58:44Z imp $

PROG=	lesskey
SRCS=	lesskey.c version.c
CLEANFILES= lesskey.1

.include "${SRCTOP}/usr.bin/less/Makefile.common"
.include <bsd.prog.mk>
