#!/bin/sh
# $FreeBSD: releng/12.0/sys/modules/drm2/radeonkmsfw/gen-makefiles 338285 2018-08-24 00:02:00Z imp $

set -e

scriptdir=$(cd $(dirname $0) && pwd)
fwdir=$scriptdir/../../../contrib/dev/drm2/radeonkmsfw

for dir in $scriptdir/*; do
	if [ ! -d $dir ]; then
		continue
	fi
	rm -rf $dir
done

for file in $fwdir/*.uu; do
	img=$(basename $file)
	img=${img%.bin.uu}
	echo "Image: $img"

	mkdir -p $scriptdir/$img
	cat > $scriptdir/$img/Makefile <<EOF
# \$FreeBSD: releng/12.0/sys/modules/drm2/radeonkmsfw/gen-makefiles 338285 2018-08-24 00:02:00Z imp $

KMOD=	radeonkmsfw_$img
IMG=	$img

.include <bsd.kmod.mk>
EOF
done
