# $FreeBSD: releng/12.0/share/doc/legal/intel_iwi/Makefile 314652 2017-03-04 11:26:40Z ngie $

FILES=		${SRCTOP}/sys/contrib/dev/iwi/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal
FILESNAME=	intel_iwi.LICENSE

.include <bsd.prog.mk>
