#
# $FreeBSD: releng/12.0/sys/modules/cxgbe/if_cxlv/Makefile 314651 2017-03-04 10:10:17Z ngie $
#

CXGBE=	${SRCTOP}/sys/dev/cxgbe
.PATH: ${CXGBE}

KMOD=	if_cxlv
SRCS=	if_cxlv.c

.include <bsd.kmod.mk>
