# $FreeBSD: releng/12.0/sys/modules/wpi/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:  ${SRCTOP}/sys/dev/wpi

KMOD    = if_wpi
SRCS    = if_wpi.c device_if.h bus_if.h pci_if.h opt_wpi.h opt_wlan.h

.include <bsd.kmod.mk>
