# $FreeBSD: releng/12.0/sys/modules/mac_ifoff/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/security/mac_ifoff

KMOD=	mac_ifoff
SRCS=	vnode_if.h \
	mac_ifoff.c

.include <bsd.kmod.mk>
