# $FreeBSD: releng/12.0/sys/modules/viawd/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/viawd

KMOD=	viawd
SRCS=	viawd.c device_if.h bus_if.h pci_if.h isa_if.h

.include <bsd.kmod.mk>
