# $FreeBSD: releng/12.0/sys/modules/rndtest/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:	${SRCTOP}/sys/dev/rndtest
KMOD	= rndtest
SRCS	= rndtest.c
SRCS   += device_if.h bus_if.h

.include <bsd.kmod.mk>
