# $FreeBSD: releng/12.0/sys/modules/geom/geom_multipath/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/geom/multipath

KMOD=	geom_multipath
SRCS=	g_multipath.c

.include <bsd.kmod.mk>
