# $FreeBSD: releng/12.0/sys/modules/aacraid/aacraid_linux/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/aacraid

KMOD=	aacraid_linux
SRCS=	aacraid_linux.c

.include <bsd.kmod.mk>
