# $FreeBSD: releng/12.0/sys/modules/sound/driver/driver/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound

KMOD=	snd_driver
SRCS=	device_if.h bus_if.h
SRCS+=	driver.c

.include <bsd.kmod.mk>
