# $FreeBSD: releng/12.0/share/doc/legal/Makefile 289393 2015-10-15 22:55:08Z bdrewery $

SUBDIR=	intel_ipw \
	intel_iwi \
	intel_iwn \
	intel_wpi \
	realtek

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
