# $FreeBSD: releng/12.0/sys/modules/ip6_mroute_mod/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/netinet6

KMOD=	ip6_mroute

SRCS=	ip6_mroute.c
SRCS+=	opt_inet6.h opt_mrouting.h

.include <bsd.kmod.mk>
