#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/12.0/usr.bin/vis/Makefile 315170 2017-03-12 18:58:44Z imp $

PROG=	vis
SRCS=	vis.c foldit.c

.PATH: ${SRCTOP}/contrib/vis
CFLAGS+=	-I${SRCTOP}/contrib/vis

.include <bsd.prog.mk>
