# $FreeBSD: releng/12.0/usr.bin/sdiff/Makefile 326632 2017-12-06 20:10:05Z bapt $

.include <src.opts.mk>

PROG=	sdiff
SRCS=	edit.c sdiff.c

MAN1=	sdiff.1

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
