#$FreeBSD: releng/12.0/sys/modules/i2c/controllers/ismt/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:		${SRCTOP}/sys/dev/ismt
KMOD		= ismt
SRCS		= device_if.h bus_if.h iicbb_if.h pci_if.h smbus_if.h \
		  ismt.c

.include <bsd.kmod.mk>
