# $FreeBSD: releng/12.0/usr.bin/clang/llvm-cxxdump/Makefile 327952 2018-01-14 00:08:34Z dim $

PROG_CXX=	llvm-cxxdump
MAN=

SRCDIR=		tools/llvm-cxxdump
SRCS+=		Error.cpp
SRCS+=		llvm-cxxdump.cpp

.include "../llvm.prog.mk"
