# $FreeBSD: releng/12.0/sys/modules/syscons/logo/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:	${SRCTOP}/sys/dev/syscons/logo

KMOD=	logo_saver
SRCS=	logo_saver.c logo.c

.include <bsd.kmod.mk>
