# $FreeBSD: releng/12.0/usr.bin/clang/llvm-cxxfilt/Makefile 327952 2018-01-14 00:08:34Z dim $

PROG_CXX=	llvm-cxxfilt
MAN=

SRCDIR=		tools/llvm-cxxfilt
SRCS+=		llvm-cxxfilt.cpp

.include "../llvm.prog.mk"
