# $FreeBSD: releng/12.0/sys/modules/iwmfw/Makefile 331665 2018-03-28 07:59:16Z eadler $

SUBDIR=	iwm3160fw \
	iwm3168fw \
	iwm7260fw \
	iwm7265fw \
	iwm7265Dfw \
	iwm8000Cfw \
	iwm8265fw

.include <bsd.subdir.mk>
