# $FreeBSD: releng/12.0/tests/Makefile.inc0 322515 2017-08-14 19:21:37Z ngie $

# tests/... doesn't conform to bsd.lib.mk and bsd.prog.mk, so specify a sane
# default for MK_CHECK_USE_SANDBOX. src.opts.mk will override the value if the
# user sets it to no.
MK_CHECK_USE_SANDBOX=	yes

.include <bsd.opts.mk>
