# $FreeBSD: releng/12.0/sys/modules/geom/geom_sunlabel/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/geom

KMOD=	geom_sunlabel
SRCS=	geom_sunlabel.c geom_sunlabel_enc.c

.include <bsd.kmod.mk>
