# $FreeBSD: releng/12.0/sys/modules/wlan_amrr/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/net80211

KMOD=	wlan_amrr
SRCS=	ieee80211_amrr.c
SRCS+=	opt_wlan.h

.include <bsd.kmod.mk>
