# $FreeBSD: releng/12.0/sys/modules/sound/driver/via82c686/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/pci

KMOD=	snd_via82c686
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	via82c686.c

.include <bsd.kmod.mk>
