# $FreeBSD: releng/12.0/libexec/rtld-elf/tests/libpythagoras/Makefile 315040 2017-03-11 00:10:40Z asomers $

.include <bsd.own.mk>

LIB=		pythagoras
SHLIB_MAJOR=	0

LIBDIR=		${TESTSBASE}/libexec/rtld-elf
SHLIBDIR=	${TESTSBASE}/libexec/rtld-elf

SRCS=		pythagoras.c

WARNS?=		6
LIBADD=		m

.include <bsd.lib.mk>
