# $FreeBSD: releng/12.0/sys/modules/if_vlan/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/net

KMOD=	if_vlan
SRCS=	if_vlan.c
SRCS+=	opt_inet.h opt_vlan.h opt_ratelimit.h

.include <bsd.kmod.mk>
