# $FreeBSD: releng/12.0/sys/modules/i2c/controllers/amdpm/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:		${SRCTOP}/sys/dev/amdpm
KMOD		= amdpm
SRCS		= device_if.h bus_if.h pci_if.h smbus_if.h \
		  amdpm.c

.include <bsd.kmod.mk>
