# $FreeBSD: releng/12.0/sys/modules/fdescfs/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/fs/fdescfs

KMOD=	fdescfs
SRCS=	vnode_if.h \
	fdesc_vfsops.c fdesc_vnops.c

.include <bsd.kmod.mk>
