# $FreeBSD: releng/12.0/usr.bin/clang/llvm-modextract/Makefile 327952 2018-01-14 00:08:34Z dim $

PROG_CXX=	llvm-modextract
MAN=

SRCDIR=		tools/llvm-modextract
SRCS=		llvm-modextract.cpp

.include "../llvm.prog.mk"
