# $FreeBSD: releng/12.0/sys/modules/syscons/dragon/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:	${SRCTOP}/sys/dev/syscons/dragon

KMOD=	dragon_saver
SRCS= 	dragon_saver.c

.include <bsd.kmod.mk>
