# $FreeBSD: releng/12.0/usr.bin/clang/llvm-symbolizer/Makefile 309124 2016-11-24 22:54:55Z dim $

PROG_CXX=	llvm-symbolizer

SRCDIR=		tools/llvm-symbolizer
SRCS+=		llvm-symbolizer.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
