# $FreeBSD: releng/12.0/sys/modules/dtb/omap4/Makefile 338397 2018-08-30 14:32:10Z manu $
# All the dts files for omap4 systems we support.
DTS=	\
	omap4-duovero-parlor.dts \
        pandaboard.dts \
	pandaboard-es.dts

LINKS=	\
	${DTBDIR}/pandaboard.dtb ${DTBDIR}/omap4-panda.dtb \
	${DTBDIR}/pandaboard-es.dtb ${DTBDIR}/omap4-panda-es.dtb

.include <bsd.dtb.mk>
