#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/12.0/usr.sbin/lpr/pac/Makefile 314475 2017-03-01 05:14:45Z ngie $

.PATH: ${.CURDIR:H}/common_source

PROG=	pac
MAN=	pac.8

CFLAGS+= -I${.CURDIR:H}/common_source

LIBADD=	lpr

.include <bsd.prog.mk>
