# $FreeBSD: releng/12.0/sys/modules/mxge/mxge_rss_ethp_z8e/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/mxge
KMOD=	mxge_rss_ethp_z8e
SRCS=	mxge_rss_ethp_z8e.c

.include <bsd.kmod.mk>
