#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: releng/12.0/share/dict/Makefile 284255 2015-06-11 04:22:17Z sjg $

# XXX MISSING:	connectives words
FILES=		README propernames web2 web2a freebsd
FILESDIR=	${BINDIR}/dict
SYMLINKS=	web2 ${FILESDIR}/words

.include <bsd.prog.mk>
