# $FreeBSD: releng/12.0/tests/sys/pjdfstest/pjdfstest/Makefile 320448 2017-06-28 09:22:45Z ngie $

PACKAGE=	tests

.PATH: ${SRCTOP}/contrib/pjdfstest

BINDIR=		${TESTSBASE}/sys/pjdfstest
PROG=		pjdfstest
MAN=

CFLAGS+=	-I${.CURDIR:H}

WARNS?=		6

.include <bsd.prog.mk>
