# $FreeBSD: releng/12.0/usr.sbin/camdd/Makefile 314659 2017-03-04 11:38:03Z ngie $

PROG=	camdd
SRCS=	camdd.c
SDIR=	${SRCTOP}/sys
LIBADD=	cam mt util pthread
NO_WTHREAD_SAFETY=	1
MAN=	camdd.8

.include <bsd.prog.mk>
