# $FreeBSD: releng/12.0/tests/sys/geom/class/Makefile 329275 2018-02-14 20:26:09Z asomers $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/sys/geom/class

TESTS_SUBDIRS+=	concat
TESTS_SUBDIRS+=	eli
TESTS_SUBDIRS+=	gate
TESTS_SUBDIRS+=	mirror
TESTS_SUBDIRS+=	nop
TESTS_SUBDIRS+=	part
TESTS_SUBDIRS+=	raid3
TESTS_SUBDIRS+=	shsec
TESTS_SUBDIRS+=	stripe
TESTS_SUBDIRS+=	uzip

${PACKAGE}FILES+=	geom_subr.sh

.include <bsd.test.mk>
