# $FreeBSD: releng/12.0/stand/defaults/Makefile 330021 2018-02-26 15:41:20Z imp $

.include <bsd.init.mk>

FILES+=	loader.conf
MAN+=	loader.conf.5

FILESDIR_loader.conf=  /boot/defaults

.include <bsd.prog.mk>
