# $FreeBSD: releng/12.0/stand/userboot/Makefile 338418 2018-09-01 02:23:45Z kevans $

.include <bsd.init.mk>

SUBDIR.yes=		test
SUBDIR.${MK_FORTH}+= userboot_4th
SUBDIR.${MK_LOADER_LUA}+= userboot_lua

.include <bsd.subdir.mk>

