# $FreeBSD: releng/12.0/usr.bin/lessecho/Makefile 315170 2017-03-12 18:58:44Z imp $

PROG=	lessecho
SRCS=	lessecho.c version.c
CLEANFILES= lessecho.1

.include "${SRCTOP}/usr.bin/less/Makefile.common"
.include <bsd.prog.mk>
