# $FreeBSD: releng/12.0/usr.sbin/fdformat/Makefile 326558 2017-12-05 05:02:46Z cy $

.PATH: ${.CURDIR:H}/fdread

PROG=	fdformat
MAN=	fdformat.8
SRCS=	fdformat.c fdutil.c

CFLAGS+= -I${.CURDIR:H}/fdread

.include <bsd.prog.mk>
