# $FreeBSD: releng/12.0/sys/modules/md/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/md

KMOD=	geom_md
SRCS=	md.c opt_md.h opt_geom.h opt_rootdevname.h vnode_if.h

.include <bsd.kmod.mk>
