# $FreeBSD: releng/12.0/usr.sbin/ctm/ctm_dequeue/Makefile 314659 2017-03-04 11:38:03Z ngie $

.PATH: ${.CURDIR:H}/ctm_rmail

PROG=	ctm_dequeue
MAN=
SRCS=	ctm_dequeue.c error.c

CFLAGS+= -I${.CURDIR:H}/ctm_rmail

WARNS?=	1

.include <bsd.prog.mk>
