# $FreeBSD: releng/12.0/sys/modules/geom/geom_linux_lvm/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/geom/linux_lvm

KMOD=	geom_linux_lvm
SRCS=	g_linux_lvm.c

.include <bsd.kmod.mk>
