# $FreeBSD: releng/12.0/sys/modules/mac_none/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/security/mac_none

KMOD=	mac_none
SRCS=	vnode_if.h \
	mac_none.c

.include <bsd.kmod.mk>
