# $FreeBSD: releng/12.0/sys/modules/syscons/daemon/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:	${SRCTOP}/sys/dev/syscons/daemon

KMOD=	daemon_saver
SRCS=	daemon_saver.c

.include <bsd.kmod.mk>
