# $FreeBSD: releng/12.0/sys/modules/nge/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/nge

KMOD=	if_nge
SRCS=	if_nge.c miibus_if.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
