# $FreeBSD: releng/12.0/sys/modules/imx/Makefile 336096 2018-07-08 19:35:41Z ian $
# Build modules specific to freescale/nxp imx-family SoCs.

SUBDIR = \
	../ffec \
	imx6_ahci \
	imx6_snvs \
	imx_i2c \
	imx_spi \
	imx_wdog \
	
.include <bsd.subdir.mk>
