# $FreeBSD: releng/12.0/lib/libclang_rt/asan-preinit/Makefile 309124 2016-11-24 22:54:55Z dim $

.include <bsd.init.mk>

LIB=		clang_rt.asan-preinit-${CRTARCH}

SRCS+=		asan/asan_preinit.cc

.include <bsd.lib.mk>
