#
# $FreeBSD: releng/12.0/usr.sbin/bsnmpd/tools/libbsnmptools/Makefile 311174 2017-01-03 22:31:05Z ngie $
#

.PATH: ${.CURDIR}

LIB=	bsnmptools

SRCS=	bsnmpimport.c bsnmpmap.c bsnmptools.c bsnmptc.c

INTERNALLIB=

.include <bsd.lib.mk>
