# Makefile for simple caller of syscall
# $FreeBSD: releng/12.0/share/examples/kld/syscall/test/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/kld/test
PROG=	call
MAN=
WARNS?=	5

.include <bsd.prog.mk>
