# $FreeBSD: releng/12.0/sys/modules/geom/geom_part/geom_part_mbr/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/geom/part

KMOD=	geom_part_mbr
SRCS=	g_part_mbr.c

SRCS+=	bus_if.h device_if.h g_part_if.h

.include <bsd.kmod.mk>
