# $FreeBSD: releng/12.0/sys/modules/iwi/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/iwi

KMOD    = if_iwi
SRCS    = if_iwi.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
