# $FreeBSD: releng/12.0/share/examples/smbfs/Makefile 314652 2017-03-04 11:26:40Z ngie $

PACKAGE=examples
FILESDIR= ${SHAREDIR}/examples/smbfs
FILES=	dot.nsmbrc

.PATH: ${SRCTOP}/contrib/smbfs/examples

SUBDIR=	print

.include <bsd.prog.mk>
