# $FreeBSD: releng/12.0/usr.sbin/fstyp/tests/Makefile 312010 2017-01-13 04:02:09Z ngie $

PACKAGE=	tests

ATF_TESTS_SH=	fstyp_test

${PACKAGE}FILES+=	dfr-01-xfat.img.bz2
${PACKAGE}FILES+=	ext2.img.bz2
${PACKAGE}FILES+=	ext3.img.bz2
${PACKAGE}FILES+=	ext4.img.bz2
${PACKAGE}FILES+=	ext4_with_label.img.bz2
${PACKAGE}FILES+=	ntfs.img.bz2
${PACKAGE}FILES+=	ntfs_with_label.img.bz2

.include <bsd.test.mk>
