# $FreeBSD: releng/12.0/sys/modules/amdsmb/Makefile 336068 2018-07-07 15:55:52Z imp $

.PATH:	${SRCTOP}/sys/dev/amdsmb

KMOD=	amdsmb
SRCS=	amdsmb.c bus_if.h device_if.h pci_if.h smbus_if.h

.include <bsd.kmod.mk>
