# $FreeBSD: releng/12.0/sys/modules/mmcnull/Makefile 320845 2017-07-09 17:02:47Z imp $

.PATH: ${.CURDIR}/../../dev/mmcnull

KMOD=	mmcnull
SRCS=	mmcnull.c device_if.h bus_if.h

.include <bsd.kmod.mk>
