# $FreeBSD: releng/12.0/sys/modules/ow/ow_temp/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/ow

KMOD=	ow_temp
SRCS=	ow_temp.c
SRCS+=	own_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
