# $FreeBSD: releng/12.0/share/examples/FreeBSD_version/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/${PROG}
PROG=	FreeBSD_version
MAN=

install:

.include <bsd.prog.mk>
