# $FreeBSD: releng/12.0/lib/libnetbsd/Makefile 316572 2017-04-06 14:36:08Z emaste $

.include <bsd.own.mk>

PACKAGE=lib${LIB}
LIB=	netbsd

CFLAGS+=	-I${.CURDIR}

SRCS+=	efun.c sockaddr_snprintf.c strsuftoll.c util.c util.h

INTERNALLIB=

.include <bsd.lib.mk>
