# $FreeBSD: releng/12.0/sys/modules/vte/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/vte

KMOD=	if_vte
SRCS=	if_vte.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
