# $FreeBSD: releng/12.0/sys/modules/ip_mroute_mod/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/netinet ${SRCTOP}/sys/netinet6

KMOD=	ip_mroute

SRCS=	ip_mroute.c
SRCS+=	opt_inet.h opt_mrouting.h

.include <bsd.kmod.mk>
