# $FreeBSD: releng/12.0/usr.sbin/periodic/Makefile 338429 2018-09-02 15:53:56Z brd $

CONFS=	periodic.conf
CONFSDIR=	/etc/defaults
SCRIPTS=periodic.sh
MAN=	periodic.8

SUBDIR=	etc

.include <bsd.prog.mk>
