#!/bin/sh -
#
#	$FreeBSD: releng/12.0/tools/tools/perforce/p4diffbranch 270727 2014-08-27 18:56:12Z jmg $
#

if [ x"$#" != x"2" ]; then
	echo "Usage: $0 <branch> <changesetnum>"
	exit 1
fi

basescript="$(realpath "$0")"
awkdiff="${basescript%/*}/awkdiff"

branch="$1"
changenum="$2"

p4 branch -o "$branch" |
	awk ' /^View:/ { doview = 1; next; } /^[^	]/ {doview = 0; next; } $1 && $2 && doview == 1 { system("p4 diff2 -du " $1 "@" changenum " " $2) }' changenum="$changenum" |
	"$awkdiff"
