# $FreeBSD: releng/12.0/usr.bin/clang/clang-tblgen/Makefile 327952 2018-01-14 00:08:34Z dim $

PROG_CXX=	clang-tblgen
MAN=

SRCDIR=		tools/clang/utils/TableGen
SRCS+=		ClangASTNodesEmitter.cpp
SRCS+=		ClangAttrEmitter.cpp
SRCS+=		ClangCommentCommandInfoEmitter.cpp
SRCS+=		ClangCommentHTMLNamedCharacterReferenceEmitter.cpp
SRCS+=		ClangCommentHTMLTagsEmitter.cpp
SRCS+=		ClangDataCollectorsEmitter.cpp
SRCS+=		ClangDiagnosticsEmitter.cpp
SRCS+=		ClangOptionDocEmitter.cpp
SRCS+=		ClangSACheckersEmitter.cpp
SRCS+=		NeonEmitter.cpp
SRCS+=		TableGen.cpp

.include "../llvm.prog.mk"
