# $FreeBSD: releng/12.0/sys/modules/ichwd/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/ichwd

KMOD=	ichwd
SRCS=	ichwd.c device_if.h bus_if.h pci_if.h isa_if.h

.include <bsd.kmod.mk>
