#	$NetBSD: Makefile,v 1.4 1999/05/11 21:02:25 augustss Exp $
# $FreeBSD: releng/12.0/usr.bin/usbhidctl/Makefile 275042 2014-11-25 14:29:10Z bapt $

PROG=	usbhidctl
SRCS=	usbhid.c

LIBADD=	usbhid

.include <bsd.prog.mk>
