# $FreeBSD: releng/12.0/usr.bin/clang/llvm-mc/Makefile 309124 2016-11-24 22:54:55Z dim $

PROG_CXX=	llvm-mc
MAN=

SRCDIR=		tools/llvm-mc
SRCS+=		Disassembler.cpp
SRCS+=		llvm-mc.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
