#!/bin/sh
#
# $FreeBSD: releng/12.0/usr.sbin/autofs/autofs/include_nis 326252 2017-11-27 12:50:26Z trasz $
#

if [ -n "$2" ]; then
	ypmatch $2 $1
	exit 0
fi

if [ -n "$1" ]; then
	ypcat -k $1
	exit 0
fi
