# $FreeBSD: releng/12.0/usr.sbin/autofs/autofs/Makefile 337340 2018-08-04 22:41:17Z brd $

CONFS=		include_ldap \
		include_nis \
		include_nis_nullfs \
		special_hosts \
		special_media \
		special_noauto \
		special_null

NO_OBJ=
CONFDIR=	/etc/autofs
CONFMODE=	755

.include <bsd.prog.mk>
