#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/12.0/usr.bin/head/Makefile 326039 2017-11-20 22:55:02Z asomers $

.include <src.opts.mk>

PROG=	head

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
