# $FreeBSD: releng/12.0/lib/libgcc_eh/Makefile 308563 2016-11-11 23:28:07Z emaste $

.include <src.opts.mk>

PACKAGE=	clibs
LIB=		gcc_eh
NO_PIC=
MK_SSP=		no
WARNS?=	2

.include "Makefile.inc"

.include <bsd.lib.mk>
