#	@(#)Makefile	8.1 (Berkeley) 6/5/93
#	$FreeBSD: releng/12.0/usr.sbin/rip6query/Makefile 314659 2017-03-04 11:38:03Z ngie $

PROG=	rip6query
MAN=	rip6query.8

CFLAGS+= -I${.CURDIR:H}/route6d

.include <bsd.prog.mk>
