# $FreeBSD: releng/12.0/usr.sbin/bsdinstall/distextract/Makefile 291348 2015-11-26 01:14:40Z bdrewery $

BINDIR= ${LIBEXECDIR}/bsdinstall
PROG=	distextract
LIBADD=	archive dpv figpar ncursesw dialog m

WARNS?=	6
MAN=

.include <bsd.prog.mk>
