# $FreeBSD: releng/12.0/sys/modules/mmc/Makefile 315430 2017-03-16 22:23:04Z marius $

.PATH: ${SRCTOP}/sys/dev/mmc

KMOD=	mmc
SRCS=	bus_if.h device_if.h mmc_subr.c mmc.c mmcbr_if.h mmcbus_if.h

.include <bsd.kmod.mk>
