# $FreeBSD: releng/12.0/usr.bin/clang/llvm-lto/Makefile 309124 2016-11-24 22:54:55Z dim $

PROG_CXX=	llvm-lto
MAN=

SRCDIR=		tools/llvm-lto
SRCS=		llvm-lto.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
