# $FreeBSD: releng/12.0/sys/modules/netgraph/vjc/Makefile 314651 2017-03-04 10:10:17Z ngie $
# $Whistle: Makefile,v 1.1 1999/01/24 06:48:07 archie Exp $

.PATH: ${SRCTOP}/sys/net

KMOD=	ng_vjc
SRCS= 	ng_vjc.c slcompress.c

.include <bsd.kmod.mk>
