# $FreeBSD: releng/12.0/sys/modules/ata/atapci/chipsets/ataintel/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	ataintel
SRCS=	ata-intel.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
