#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: releng/12.0/usr.bin/caesar/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG=	caesar
LIBADD=	m
SCRIPTS=rot13.sh
MAN=	caesar.6
MLINKS=	caesar.6 rot13.6

.include <bsd.prog.mk>
