# $FreeBSD: releng/12.0/sys/modules/geom/geom_raid3/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/geom/raid3

KMOD=	geom_raid3
SRCS=	g_raid3.c
SRCS+=	g_raid3_ctl.c

.include <bsd.kmod.mk>
