# $FreeBSD: releng/12.0/usr.bin/diff/Makefile 334894 2018-06-09 20:24:17Z bapt $

.include <src.opts.mk>

PROG=	diff
SRCS=	diff.c diffdir.c diffreg.c xmalloc.c pr.c

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
