# $FreeBSD: releng/12.0/tools/tools/ath/ath_ee_9287_print/Makefile 264925 2014-04-25 19:25:05Z imp $

.PATH:  ${.CURDIR}/../../../../sys/dev/ath/ath_hal

PROG=	ath_ee_9287_print
SRCS=	main.c eeprom.c 9287.c
MAN=

.include <../Makefile.inc>

.include <bsd.prog.mk>
