# $FreeBSD: releng/12.0/usr.bin/sort/tests/Makefile 335403 2018-06-20 03:10:49Z kevans $

PACKAGE=	tests

NETBSD_ATF_TESTS_SH=	sort_test

${PACKAGE}FILES+=		d_any_char_dflag_out.txt
${PACKAGE}FILES+=		d_any_char_fflag_out.txt
${PACKAGE}FILES+=		d_any_char_iflag_out.txt
${PACKAGE}FILES+=		d_any_char_in.txt

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
