# $FreeBSD: releng/12.0/usr.bin/soelim/tests/Makefile 315776 2017-03-23 03:28:24Z ngie $

PACKAGE=	tests

ATF_TESTS_SH=	soelim_test

${PACKAGE}FILES+=		nonexisting.in \
		basic.in \
		basic \
		basic.out \
		basic-with-space.in \
		basic-with-space.out

.include <bsd.test.mk>
