# $FreeBSD: releng/12.0/sbin/ddb/Makefile 337623 2018-08-11 13:25:39Z brd $

CONFS=	ddb.conf
PACKAGE=runtime
PROG=	ddb
SRCS=	ddb.c ddb_capture.c ddb_script.c
MAN=	ddb.8

LIBADD=	kvm

.include <bsd.prog.mk>
