#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/12.0/usr.bin/sed/Makefile 336929 2018-07-30 19:41:54Z pfg $

.include <src.opts.mk>

PROG=	sed
SRCS=	compile.c main.c misc.c process.c

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
