# Copyright (C) 1999-2000 by Maksim Yevmenkin <m_evmenkin@yahoo.com>
#
# $FreeBSD: releng/12.0/sys/modules/if_tap/Makefile 332122 2018-04-06 17:35:35Z brooks $

.PATH: ${SRCTOP}/sys/net

KMOD=	if_tap
SRCS=	if_tap.c opt_inet.h vnode_if.h

.include <bsd.kmod.mk>
