#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: releng/12.0/sbin/clri/Makefile 328426 2018-01-26 00:58:32Z mckusick $

PACKAGE=runtime
PROG=	clri
MAN=	clri.8
LIBADD=	ufs
WARNS?=	2

.include <bsd.prog.mk>
