# $FreeBSD: releng/12.0/tools/tools/net80211/wesside/wesside/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG=	wesside
BINDIR=	/usr/local/bin
LIBADD=	z
CFLAGS=-g
MAN=
SRCS=wesside.c aircrack-ptw-lib.c

.include <bsd.prog.mk>
