
# $FreeBSD: releng/12.0/sys/modules/ppi/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:	${SRCTOP}/sys/dev/ppbus
KMOD=	ppi
SRCS=	bus_if.h device_if.h ppbus_if.h \
	opt_ppb_1284.h \
	ppi.c ppb_1284.c

.include <bsd.kmod.mk>
