# $FreeBSD: releng/12.0/sys/modules/cxgb/Makefile 323556 2017-09-13 17:49:23Z np $

SYSDIR?=${SRCTOP}/sys
.include "${SYSDIR}/conf/kern.opts.mk"

SUBDIR= cxgb
SUBDIR+= cxgb_t3fw

.include <bsd.subdir.mk>
