# $FreeBSD: releng/12.0/usr.bin/fortune/Makefile.inc 314893 2017-03-08 05:31:54Z ngie $

FORTUNE_SRC=	${SRCTOP}/usr.bin/fortune
FORTUNE_OBJ=	${OBJTOP}/usr.bin/fortune

.include "${SRCTOP}/usr.bin/Makefile.inc"
