#	@(#)Makefile	8.1 (Berkeley) 5/31/93
#
# $FreeBSD: releng/12.0/usr.bin/fortune/Makefile 314831 2017-03-07 04:33:17Z ngie $

SUBDIR=	fortune strfile datfiles unstr

SUBDIR_DEPEND_datfiles=	strfile

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
