# $FreeBSD: releng/12.0/sys/modules/geom/geom_part/Makefile 312910 2017-01-28 02:22:15Z nyan $

SUBDIR=	geom_part_apm \
	geom_part_bsd \
	geom_part_bsd64 \
	geom_part_ebr \
	geom_part_gpt \
	geom_part_ldm \
	geom_part_mbr \
	geom_part_vtoc8

.include <bsd.subdir.mk>
