#$FreeBSD: releng/12.0/sys/modules/mxge/mxge/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/mxge

KMOD=	if_mxge
SRCS=	if_mxge.c device_if.h bus_if.h pci_if.h opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
