# $FreeBSD: releng/12.0/sys/modules/syscons/plasma/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:	${SRCTOP}/sys/dev/syscons/plasma

KMOD=	plasma_saver
SRCS=	fp16.c plasma_saver.c

.include <bsd.kmod.mk>
