# $FreeBSD: releng/12.0/usr.bin/bzip2recover/Makefile 315170 2017-03-12 18:58:44Z imp $

BZ2DIR=	${SRCTOP}/contrib/bzip2
.PATH: ${BZ2DIR}

PROG=	bzip2recover
MAN=

NO_WMISSING_VARIABLE_DECLARATIONS=

.include <bsd.prog.mk>
