# $FreeBSD: releng/12.0/sys/modules/bfe/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/bfe

KMOD=	if_bfe
SRCS=	if_bfe.c miibus_if.h miidevs.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
