# $FreeBSD: releng/12.0/sys/modules/mac_veriexec_sha1/Makefile 335399 2018-06-20 00:41:30Z stevek $

.PATH: ${.PARSEDIR:H:H}/security/mac_veriexec
.PATH: ${.PARSEDIR:H:H}/crypto

KMOD=	mac_veriexec_sha1
SRCS=	mac_veriexec_sha1.c sha1.c

.include <bsd.kmod.mk>

