# Makefile for kld char device driver.
# $FreeBSD: releng/12.0/share/examples/kld/cdev/module/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/kld/${KMOD}/module
KMOD=	cdev
SRCS=	cdev.c cdevmod.c

.include <bsd.kmod.mk>
