# $FreeBSD: releng/12.0/sys/modules/netgraph/bpf/Makefile 314651 2017-03-04 10:10:17Z ngie $
# $Whistle: Makefile,v 1.1 1999/12/03 01:44:28 archie Exp $

.PATH: ${SRCTOP}/sys/net

KMOD=	ng_bpf
SRCS=	opt_bpf.h ng_bpf.c bpf_filter.c

.include <bsd.kmod.mk>
