# $FreeBSD: releng/12.0/cddl/usr.sbin/zfsd/Makefile 305019 2016-08-29 19:07:48Z ngie $

.include "Makefile.common"

PROG_CXX=	zfsd
MAN=		zfsd.8

.include <bsd.prog.mk>

# The unittests require devel/googletest and devel/googlemock from ports.
# Don't automatically build them.
SUBDIR=
