# $FreeBSD: releng/12.0/sys/modules/ow/ow/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/ow

KMOD=	ow
SRCS=	ow.c
SRCS+=	own_if.c own_if.h owll_if.c owll_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
