# $FreeBSD: releng/12.0/sys/modules/udf_iconv/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:	${SRCTOP}/sys/fs/udf
KMOD=	udf_iconv
SRCS=	udf_iconv.c

CFLAGS+= -I${SRCTOP}/sys/

.include <bsd.kmod.mk>
