# $FreeBSD: releng/12.0/sys/modules/mac_seeotheruids/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/security/mac_seeotheruids

KMOD=	mac_seeotheruids
SRCS=	vnode_if.h \
	mac_seeotheruids.c

.include <bsd.kmod.mk>
