# $FreeBSD: releng/12.0/sys/modules/mac_lomac/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/security/mac_lomac

KMOD=	mac_lomac
SRCS=	vnode_if.h \
	mac_lomac.c

.include <bsd.kmod.mk>
