# $FreeBSD: releng/12.0/usr.bin/cmp/tests/Makefile 311572 2017-01-07 00:59:06Z asomers $

.include <bsd.own.mk>

ATF_TESTS_SH+=		cmp_test2
NETBSD_ATF_TESTS_SH=	cmp_test

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
