# $FreeBSD: releng/12.0/sys/modules/ae/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/ae

KMOD=	if_ae
SRCS=	if_ae.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
