# $FreeBSD: releng/12.0/usr.bin/xolint/Makefile 319999 2017-06-16 06:29:21Z phil $

.include <src.opts.mk>

LIBXOSRC=	${SRCTOP}/contrib/libxo

.PATH:
.PATH:	${LIBXOSRC}/xolint

SCRIPTS= xolint.pl
MAN=	xolint.1

.include <bsd.prog.mk>
