# $FreeBSD: releng/12.0/share/doc/legal/intel_wpi/Makefile 314652 2017-03-04 11:26:40Z ngie $

FILES=          ${SRCTOP}/sys/contrib/dev/wpi/LICENSE
FILESDIR=       ${SHAREDIR}/doc/legal
FILESNAME=	intel_wpi.LICENSE

.include <bsd.prog.mk>

