# $FreeBSD: releng/12.0/sys/modules/sdhci/Makefile 320856 2017-07-10 03:38:07Z imp $

.PATH: ${SRCTOP}/sys/dev/sdhci

KMOD=	sdhci
SRCS=	sdhci.c sdhci.h sdhci_if.c sdhci_if.h device_if.h bus_if.h mmcbr_if.h opt_mmccam.h opt_cam.h

.include <bsd.kmod.mk>
