# $FreeBSD: releng/12.0/gnu/usr.bin/binutils/libbfd/Makefile.arm 322521 2017-08-14 22:25:20Z imp $

.if ${TARGET_ARCH:Marm*eb} != ""
DEFAULT_VECTOR=	bfd_elf32_bigarm_vec
.else
DEFAULT_VECTOR=	bfd_elf32_littlearm_vec
.endif

SRCS+=	cpu-arm.c \
	elf32.c \
	elf32-arm.c \
	elf32-gen.c \
	elf32-target.h \
	elflink.c

VECS+=	${DEFAULT_VECTOR}
.if ${TARGET_ARCH:Marm*eb} != ""
VECS+=	bfd_elf32_littlearm_vec
.else
VECS+=	bfd_elf32_bigarm_vec
.endif
