# $FreeBSD: releng/12.0/sys/modules/amr/amr_linux/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/amr

KMOD=	amr_linux
SRCS=	amr_linux.c device_if.h bus_if.h

.include <bsd.kmod.mk>
