#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/12.0/usr.bin/locate/code/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=	locate.code
CFLAGS+=-I${.CURDIR}/../locate 
MAN=
BINDIR=	${LIBEXECDIR}

.include <bsd.prog.mk>
