# $FreeBSD: releng/12.0/tests/sys/netpfil/pf/ioctl/Makefile 332102 2018-04-06 15:03:48Z kp $

PACKAGE=	tests

TESTSDIR=       ${TESTSBASE}/sys/netpfil/pf/ioctl

ATF_TESTS_C += \
	validation

.include <bsd.test.mk>
