# $FreeBSD: releng/12.0/share/doc/llvm/Makefile 314652 2017-03-04 11:26:40Z ngie $

SUBDIR=		clang

SRCDIR=		${SRCTOP}/contrib/llvm

.PATH: ${SRCDIR} ${SRCDIR}/lib/Support

FILESGROUPS=	TOP
TOP=		LICENSE.TXT COPYRIGHT.regex
TOPDIR=		${DOCDIR}/llvm

.include <bsd.prog.mk>
