# $FreeBSD: releng/12.0/usr.bin/clang/llvm-profdata/Makefile 309124 2016-11-24 22:54:55Z dim $

PROG_CXX=	llvm-profdata

SRCDIR=		tools/llvm-profdata
SRCS+=		llvm-profdata.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
