# $FreeBSD: releng/12.0/usr.sbin/bsnmpd/tools/Makefile 311174 2017-01-03 22:31:05Z ngie $
# Author: Shteryana Shopova <syrinx@FreeBSD.org>

SUBDIR=	libbsnmptools \
	bsnmptools

SUBDIR_DEPEND_bsnmptools=	libbsnmptools

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
