# $FreeBSD: releng/12.0/usr.sbin/etcupdate/Makefile 322515 2017-08-14 19:21:37Z ngie $

.include <src.opts.mk>

SCRIPTS=etcupdate.sh
MAN=	etcupdate.8

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
