# $FreeBSD: releng/12.0/lib/libc/tests/inet/Makefile 305358 2016-09-03 18:11:48Z ngie $

.include <bsd.own.mk>

NETBSD_ATF_TESTS_C+=	inet_addr_test
NETBSD_ATF_TESTS_C+=	inet_network_test

.include "../Makefile.netbsd-tests"

.include <bsd.test.mk>
