# $FreeBSD: releng/12.0/usr.bin/clang/llvm-extract/Makefile 309124 2016-11-24 22:54:55Z dim $

PROG_CXX=	llvm-extract

SRCDIR=		tools/llvm-extract
SRCS+=		llvm-extract.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
