# $FreeBSD: releng/12.0/share/keys/pkg/trusted/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILES=	pkg.freebsd.org.2013102301

FILESDIR=	${SHAREDIR}/keys/pkg/trusted
FILESMODE=	644

.include <bsd.prog.mk>
