# $FreeBSD: releng/12.0/sys/modules/i2c/isl/Makefile 331868 2018-04-01 18:22:24Z ian $

.PATH:		${SRCTOP}/sys/dev/isl
KMOD		= isl
SRCS		= isl.c device_if.h bus_if.h iicbus_if.h opt_platform.h

.include <bsd.kmod.mk>
