# $FreeBSD: releng/12.0/usr.sbin/ntp/doc/drivers/scripts/Makefile 314472 2017-03-01 04:54:06Z ngie $

.include <src.opts.mk>

FILESDIR=	${SHAREDIR}/doc/ntp/drivers/scripts

.if ${MK_HTML} != "no"
FILES=	footer.txt style.css
.endif

.PATH: ${SRCTOP}/contrib/ntp/html/drivers/scripts

.include <bsd.prog.mk>
