# $FreeBSD: releng/12.0/sys/modules/amdsbwd/Makefile 336134 2018-07-09 14:18:03Z ian $

.PATH:  ${SRCTOP}/sys/dev/amdsbwd
KMOD    = amdsbwd
SRCS    = amdsbwd.c
SRCS    += device_if.h bus_if.h pci_if.h isa_if.h opt_amdsbwd.h

.include <bsd.kmod.mk>
