# $FreeBSD: releng/12.0/usr.bin/clang/llvm-rtdyld/Makefile 309124 2016-11-24 22:54:55Z dim $

PROG_CXX=	llvm-rtdyld
MAN=

SRCDIR=		tools/llvm-rtdyld
SRCS+=		llvm-rtdyld.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
