# $FreeBSD: releng/12.0/sys/modules/i2c/smb/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:		${SRCTOP}/sys/dev/smbus
KMOD		= smb
SRCS		= device_if.h bus_if.h smbus_if.h \
		  smb.c

.include <bsd.kmod.mk>
