# $FreeBSD: releng/12.0/sys/modules/sound/driver/ad1816/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/isa

KMOD=	snd_ad1816
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h
SRCS+=	ad1816.c

.include <bsd.kmod.mk>
