# $FreeBSD: releng/12.0/sys/modules/ti/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/ti

KMOD=	if_ti
SRCS=	if_ti.c device_if.h bus_if.h pci_if.h opt_ti.h

.include <bsd.kmod.mk>
