# $FreeBSD: releng/12.0/libexec/blacklistd-helper/Makefile 301226 2016-06-02 19:06:04Z lidl $

BLACKLIST_DIR=${SRCTOP}/contrib/blacklist

SCRIPTS=	${BLACKLIST_DIR}/libexec/blacklistd-helper

.include <bsd.prog.mk>
