#	$FreeBSD: releng/12.0/tools/tools/ath/Makefile 269762 2014-08-09 18:17:49Z adrian $

SUBDIR=	arcode athdebug athdecode athkey athpoke athprom athrd athregs athalq
SUBDIR+=	athstats ath_prom_read athradar athaggrstats
SUBDIR+=	ath_ee_v14_print ath_ee_v4k_print ath_ee_9287_print ath_ee_9300_print
SUBDIR+=	athsurvey athratestats athspectral

.include <bsd.subdir.mk>
