#
# $FreeBSD: releng/12.0/tools/tools/ether_reflect/Makefile 291738 2015-12-04 03:17:47Z bdrewery $
#
# A Makefile that builds both the ether_reflect program and its manual page.

PROG=   ether_reflect
LIBADD=	pcap
CFLAGS+=-DHAVE_SNPRINTF

.include <bsd.prog.mk>
