# $FreeBSD: releng/12.0/sys/modules/siis/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/siis

KMOD=	siis
SRCS=	siis.c siis.h device_if.h bus_if.h pci_if.h opt_cam.h

.include <bsd.kmod.mk>
