# $FreeBSD: releng/12.0/share/doc/llvm/clang/Makefile 314652 2017-03-04 11:26:40Z ngie $

SRCDIR=		${SRCTOP}/contrib/llvm/tools/clang

.PATH: ${SRCDIR}

FILESGROUPS=	TOP
TOP=		LICENSE.TXT
TOPDIR=		${DOCDIR}/llvm/clang

.include <bsd.prog.mk>
