# $FreeBSD: releng/12.0/sys/modules/mmcsd/Makefile 317981 2017-05-08 20:58:32Z marius $

.PATH: ${SRCTOP}/sys/dev/mmc

KMOD=	mmcsd
SRCS=	bus_if.h device_if.h mmcbr_if.h mmcbus_if.h mmcsd.c

.include <bsd.kmod.mk>
