# $FreeBSD: releng/12.0/sys/modules/i2c/Makefile 337033 2018-08-01 08:24:34Z rpokala $

SUBDIR = \
	controllers \
	cyapa \
	ds1307 \
	ds13rtc \
	ds1672 \
	ds3231 \
	icee \
	if_ic \
	iic \
	iicbb \
	iicbus \
	iicsmb \
	isl \
	isl12xx \
	jedec_dimm \
	nxprtc \
	rtc8583 \
	s35390a \
	smb \
	smbus \

.include <bsd.subdir.mk>
