# $FreeBSD: releng/12.0/tools/tools/vimage/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG=	vimage
LIBADD=	jail

WARNS?=	2
CFLAGS+= -I../../../sys

MAN=	vimage.8

BINDIR?=	/usr/sbin

.include <bsd.prog.mk>
