# $FreeBSD: releng/12.0/sys/modules/epic/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/sparc64/ebus

KMOD=	epic
SRCS=	device_if.h epic.c bus_if.h ofw_bus_if.h

.include <bsd.kmod.mk>
