# $FreeBSD: releng/12.0/sys/modules/geom/geom_sched/Makefile.inc 314651 2017-03-04 10:10:17Z ngie $
# included by geom_sched children

.PATH: ${SRCTOP}/sys/geom/sched

# 6.x needs this path
#CFLAGS += -I${SRCTOP}/sys/geom/sched

# .include <bsd.kmod.mk>
