# $FreeBSD: releng/12.0/sys/modules/ffec/Makefile 319899 2017-06-13 14:07:13Z ian $

.PATH: ${SRCTOP}/sys/dev/ffec

KMOD=	if_ffec
SRCS=	if_ffec.c miibus_if.h device_if.h bus_if.h pci_if.h ofw_bus_if.h opt_global.h

.include <bsd.kmod.mk>
