# $FreeBSD: releng/12.0/sys/modules/acpi/acpi_ibm/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:		${SRCTOP}/sys/dev/acpi_support
KMOD=		acpi_ibm
SRCS=		acpi_ibm.c opt_acpi.h device_if.h bus_if.h acpi_if.h
SRCS+=		opt_ddb.h

.include <bsd.kmod.mk>
