# $FreeBSD: releng/12.0/sys/modules/amdtemp/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:	${SRCTOP}/sys/dev/amdtemp

KMOD=	amdtemp
SRCS=	amdtemp.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
