# $FreeBSD: releng/12.0/sys/modules/mac_veriexec_sha512/Makefile 335399 2018-06-20 00:41:30Z stevek $

.PATH: ${.CURDIR}/../../security/mac_veriexec
.PATH: ${.CURDIR}/../../crypto/sha2

KMOD=	mac_veriexec_sha512
SRCS=	mac_veriexec_sha512.c sha512c.c

.include <bsd.kmod.mk>

