# $FreeBSD: releng/12.0/usr.bin/ident/tests/Makefile 315776 2017-03-23 03:28:24Z ngie $

PACKAGE=	tests

ATF_TESTS_SH=	ident_test
${PACKAGE}FILES+=	\
		test.in \
		test.out \
		testnoid

.include <bsd.test.mk>
