# $FreeBSD: releng/12.0/lib/librss/Makefile 307831 2016-10-23 20:41:25Z adrian $

PACKAGE=	lib${LIB}
SHLIBDIR?=	/lib

.include <src.opts.mk>

INCS=	librss.h
LIB=	rss
SHLIB_MAJOR=	1

SRCS=librss.c

.include <bsd.lib.mk>
