# $FreeBSD: releng/12.0/usr.bin/clang/llvm-bcanalyzer/Makefile 327952 2018-01-14 00:08:34Z dim $

PROG_CXX=	llvm-bcanalyzer

SRCDIR=		tools/llvm-bcanalyzer
SRCS+=		llvm-bcanalyzer.cpp

.include "../llvm.prog.mk"
