# $FreeBSD: releng/12.0/usr.sbin/mlxcontrol/Makefile 314659 2017-03-04 11:38:03Z ngie $

PROG=	mlxcontrol
MAN=	mlxcontrol.8
SRCS=	command.c config.c interface.c util.c

CFLAGS+= -I${SRCTOP}/sys

WARNS?=	2

.include <bsd.prog.mk>
