# $FreeBSD: releng/12.0/sys/modules/wbwd/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/wbwd

KMOD=	wbwd
SRCS=	wbwd.c
SRCS+=	bus_if.h device_if.h isa_if.h

.include <bsd.kmod.mk>
