#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: releng/12.0/sbin/dumpfs/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=runtime
PROG=	dumpfs
WARNS?=	2
LIBADD=	ufs
MAN=	dumpfs.8

.include <bsd.prog.mk>
