# $FreeBSD: releng/12.0/lib/libc/tests/regex/Makefile 328240 2018-01-22 02:44:41Z kevans $

PACKAGE=	tests

.include "Makefile.inc"
.include "${.CURDIR:H}/Makefile.netbsd-tests"
.include <bsd.test.mk>
