#
# $FreeBSD: releng/12.0/sys/modules/tests/callout_test/Makefile 314651 2017-03-04 10:10:17Z ngie $
#

.PATH: ${SRCTOP}/sys/tests/callout_test

KMOD=	callout_test
SRCS=	callout_test.c

#
# Enable full debugging
#
#CFLAGS += -g

.include <bsd.kmod.mk>
