# $FreeBSD: releng/12.0/sys/modules/i2c/iicsmb/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:		${SRCTOP}/sys/dev/iicbus
KMOD		= iicsmb
SRCS		= device_if.h bus_if.h iicbus_if.h \
		  smbus_if.h iicsmb.c

.include <bsd.kmod.mk>
