
# $FreeBSD: releng/12.0/sys/modules/lpt/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:	${SRCTOP}/sys/dev/ppbus
KMOD=	lpt
SRCS=	bus_if.h device_if.h ppbus_if.h \
	opt_lpt.h \
	lpt.c

.include <bsd.kmod.mk>
