# $FreeBSD: releng/12.0/lib/geom/virstor/Makefile 314656 2017-03-04 11:33:01Z ngie $

PACKAGE=runtime
.PATH: ${.CURDIR:H:H}/misc ${SRCTOP}/sys/geom/virstor

GEOM_CLASS=	virstor

SRCS+=	binstream.c
SRCS+=	g_virstor_md.c

.include <bsd.lib.mk>
