# $FreeBSD: releng/12.0/cddl/lib/libumem/Makefile 314654 2017-03-04 11:30:04Z ngie $

.PATH: ${SRCTOP}/cddl/compat/opensolaris/lib/libumem

LIB=	umem
SRCS=	umem.c
WARNS?=	3
CFLAGS+= -I${SRCTOP}/cddl/compat/opensolaris/lib/libumem

.include <bsd.lib.mk>
