# $FreeBSD: releng/12.0/sys/modules/nctgpio/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:	${SRCTOP}/sys/dev/nctgpio
KMOD=	nctgpio
SRCS=	nctgpio.c
SRCS+=	device_if.h bus_if.h isa_if.h gpio_if.h opt_platform.h

.include <bsd.kmod.mk>
