# $FreeBSD: releng/12.0/sys/modules/rtwnfw/Makefile 312680 2017-01-24 02:35:38Z kevlo $

SUBDIR=	rtwnrtl8188eu rtwnrtl8192cT rtwnrtl8192cU rtwnrtl8192eu rtwnrtl8812au \
	rtwnrtl8821au rtwnrtl8192cE rtwnrtl8192cEB

.include <bsd.subdir.mk>
