# $FreeBSD: releng/12.0/sys/modules/ata/atapci/chipsets/atacypress/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	atacypress
SRCS=	ata-cypress.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
