#$FreeBSD: releng/12.0/sys/modules/chromebook_platform/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/chromebook_platform
KMOD= chromebook_platform
SRCS= chromebook_platform.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
