# $FreeBSD: releng/12.0/release/picobsd/tinyware/view/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=view
SRCS=view.c
CFLAGS+=-I/usr/local/include
LDADD+=-L/usr/local/lib -lpng -lvgl -lz -lm
MAN=

.include <bsd.prog.mk>
