# $FreeBSD: releng/12.0/sys/modules/ata/ataisa/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/ata

KMOD=	ataisa
SRCS=	ata-isa.c
SRCS+=	ata_if.h bus_if.h device_if.h isa_if.h

.include <bsd.kmod.mk>
