# $FreeBSD: releng/12.0/usr.sbin/ntp/doc/icons/Makefile 314472 2017-03-01 04:54:06Z ngie $

.include <src.opts.mk>

FILESDIR=	${SHAREDIR}/doc/ntp/icons

.if ${MK_HTML} != "no"
FILES=	home.gif mail2.gif sitemap.png
.endif

.PATH: ${SRCTOP}/contrib/ntp/html/icons

.include <bsd.prog.mk>
