# $FreeBSD: releng/12.0/sys/modules/i2c/cyapa/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:		${SRCTOP}/sys/dev/cyapa
KMOD		= cyapa
SRCS		= cyapa.c device_if.h bus_if.h iicbus_if.h vnode_if.h

.include <bsd.kmod.mk>
