# $FreeBSD: releng/12.0/sys/modules/bios/smbios/Makefile 314651 2017-03-04 10:10:17Z ngie $
#

.PATH:  ${SRCTOP}/sys/x86/bios

KMOD=	smbios
SRCS=	smbios.c \
	bus_if.h device_if.h

.include <bsd.kmod.mk>
