# $FreeBSD: releng/12.0/sys/modules/joy/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/joy

KMOD=	joy
SRCS=	bus_if.h device_if.h isa_if.h joy.c joy_isa.c

.include <bsd.kmod.mk>
