# $FreeBSD: releng/12.0/lib/libutil/tests/Makefile 321201 2017-07-19 14:07:38Z emaste $

TAP_TESTS_C+=	flopen_test
TAP_TESTS_C+=	grp_test
TAP_TESTS_C+=	humanize_number_test
TAP_TESTS_C+=	pidfile_test
TAP_TESTS_C+=	trimdomain_test
TAP_TESTS_C+=	trimdomain-nodomain_test

WARNS?=		2
LIBADD+=	util

.include <bsd.test.mk>
