# $FreeBSD: releng/12.0/lib/libc/mips/string/Makefile.inc 314556 2017-03-02 17:05:52Z brooks $

MDSRCS+= \
	bcmp.S \
	bcopy.S \
	bzero.S \
	ffs.S \
	memcpy.S \
	memmove.S \
	strchr.S \
	strcmp.S \
	strlen.S \
	strrchr.S
