# $FreeBSD: releng/12.0/sys/modules/sge/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/sge

KMOD=	if_sge
SRCS=	if_sge.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
