# $FreeBSD: releng/12.0/tests/sys/geom/class/nop/Makefile 310803 2016-12-30 02:22:38Z asomers $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/sys/geom/class/${.CURDIR:T}

ATF_TESTS_SH+=	nop_test

.include <bsd.test.mk>
