#	From: @(#)Makefile	8.2 (Berkeley) 2/28/94
# $FreeBSD: releng/12.0/share/doc/smm/08.sendmailop/Makefile 314652 2017-03-04 11:26:40Z ngie $

VOLUME=		smm/08.sendmailop
SRCS=		op.me
MACROS=		-me
USE_PIC=
USE_EQN=
SRCDIR=		${SRCTOP}/contrib/sendmail/doc/op

.include <bsd.doc.mk>
