# $FreeBSD: releng/12.0/sys/modules/cryptodev/Makefile 332122 2018-04-06 17:35:35Z brooks $

.PATH:	${SRCTOP}/sys/opencrypto
KMOD	= cryptodev
SRCS	= cryptodev.c
SRCS	+= bus_if.h device_if.h

.include <bsd.kmod.mk>
