# $FreeBSD: releng/12.0/sys/modules/ntb/ntb_transport/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:  ${SRCTOP}/sys/dev/ntb

KMOD    = ntb_transport
SRCS    = ntb_transport.c
SRCS += device_if.h bus_if.h ntb_if.h

.include <bsd.kmod.mk>
