# $FreeBSD: releng/12.0/sys/modules/sound/driver/t4dwave/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/pci

KMOD=	snd_t4dwave
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	t4dwave.c

.include <bsd.kmod.mk>
