#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/12.0/sbin/sysctl/Makefile 337624 2018-08-11 13:28:03Z brd $

PACKAGE=runtime
CONFS=	sysctl.conf
PROG=	sysctl
WARNS?=	3
MAN=	sysctl.8

.include <bsd.prog.mk>
