# $FreeBSD: releng/12.0/usr.sbin/bsnmpd/modules/snmp_pf/Makefile 335885 2018-07-03 08:44:40Z harti $
#
# Author: Philip Paeps <philip@freebsd.org>

MOD=	pf
SRCS=	pf_snmp.c

XSYM=	begemotPf
DEFS=	${MOD}_tree.def
BMIBS=	BEGEMOT-PF-MIB.txt

.include <bsd.snmpmod.mk>
