# $FreeBSD: releng/12.0/tests/sys/cddl/zfs/tests/cli_root/zpool_import/blockfiles/Makefile 329867 2018-02-23 16:31:00Z asomers $

.include <src.opts.mk>

PACKAGE=tests
TESTSDIR=${TESTSBASE}/sys/cddl/zfs/tests/cli_root/zpool_import/blockfiles
FILESDIR=${TESTSDIR}

${PACKAGE}FILES+=	README
${PACKAGE}FILES+=	unclean_export.dat.bz2

.include <bsd.test.mk>
