# $FreeBSD: releng/12.0/tools/tools/netrate/tcpp/Makefile 264400 2014-04-13 05:21:56Z imp $

PROG=	tcpp
INCS=	tcpp.h
MAN=
SRCS=	tcpp.c tcpp_client.c tcpp_server.c tcpp_util.c
WARNS?=	3

.include <bsd.prog.mk>
