# $FreeBSD: releng/12.0/sys/modules/mac_test/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/security/mac_test

KMOD=	mac_test
SRCS=	vnode_if.h \
	mac_test.c

.include <bsd.kmod.mk>
