#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: releng/12.0/share/skel/Makefile 334841 2018-06-08 15:05:26Z brd $

FILES=		dot.cshrc dot.login dot.login_conf dot.mailrc dot.profile \
		dot.shrc dot.mail_aliases
FILESDIR=	${SHAREDIR}/skel
FILESMODE=	0644
FILESMODE_dot.mail_aliases=	0600

.include <bsd.prog.mk>
