# $FreeBSD: releng/12.0/tests/sys/geom/class/gate/Makefile 311893 2017-01-10 20:35:09Z asomers $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/sys/geom/class/${.CURDIR:T}

ATF_TESTS_SH+=	ggate_test

.include <bsd.test.mk>
