# $FreeBSD: releng/12.0/sys/modules/am335x_dmtpps/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/arm/ti/am335x

KMOD=	am335x_dmtpps
SRCS=	am335x_dmtpps.c

SRCS+= bus_if.h device_if.h ofw_bus_if.h

.include <bsd.kmod.mk>
