# $FreeBSD: releng/12.0/sys/modules/wlan_wep/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/net80211

KMOD=	wlan_wep
SRCS=	ieee80211_crypto_wep.c
SRCS+=	opt_wlan.h

.include <bsd.kmod.mk>
