 # $FreeBSD: releng/12.0/sys/modules/exca/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/exca

KMOD=	exca
SRCS=	exca.c device_if.h bus_if.h power_if.h card_if.h pccarddevs.h

.include <bsd.kmod.mk>
