# $FreeBSD: releng/12.0/usr.sbin/cpucontrol/Makefile 308218 2016-11-02 16:15:49Z avg $

PROG=	cpucontrol
MAN=	cpucontrol.8
SRCS=	cpucontrol.c intel.c amd.c amd10h.c via.c

NO_WCAST_ALIGN=

.include <bsd.prog.mk>
