# $FreeBSD: releng/12.0/sys/modules/ipfw_nptv6/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/netpfil/ipfw/nptv6

KMOD=	ipfw_nptv6
SRCS=	ip_fw_nptv6.c nptv6.c opt_ipfw.h

.include <bsd.kmod.mk>
