# $FreeBSD: releng/12.0/sys/modules/iwn/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:  ${SRCTOP}/sys/dev/iwn

KMOD    = if_iwn
SRCS    = if_iwn.c device_if.h bus_if.h pci_if.h opt_iwn.h opt_wlan.h

.include <bsd.kmod.mk>
