
# $FreeBSD: releng/12.0/sys/modules/plip/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:	${SRCTOP}/sys/dev/ppbus
KMOD=	plip
SRCS=	bus_if.h device_if.h ppbus_if.h \
	opt_plip.h \
	if_plip.c

.include <bsd.kmod.mk>
