# $FreeBSD: releng/12.0/tools/tools/wtap/vis_map/Makefile 264400 2014-04-13 05:21:56Z imp $

BINDIR?=	/usr/local/bin/
PROG=	vis_map
SRC=	vis_map.c
MAN=

CFLAGS+=	-I${.CURDIR}/../../../../sys/dev/wtap/

.include <bsd.prog.mk>
