# $FreeBSD: releng/12.0/sys/modules/mac_biba/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/security/mac_biba

KMOD=	mac_biba
SRCS=	vnode_if.h \
	mac_biba.c

.include <bsd.kmod.mk>
