# $FreeBSD: releng/12.0/usr.sbin/prometheus_sysctl_exporter/Makefile 310354 2016-12-21 08:29:44Z ed $

PROG=	prometheus_sysctl_exporter
MAN=	prometheus_sysctl_exporter.8

LIBADD=	m z

.include <bsd.prog.mk>
