# $FreeBSD: releng/12.0/sys/modules/usb/cfumass/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/usb/storage
KMOD=	cfumass

SRCS=	bus_if.h device_if.h opt_bus.h opt_usb.h usb_if.h usbdevs.h \
	cfumass.c

.include <bsd.kmod.mk>
