# $FreeBSD: releng/12.0/tools/tools/net80211/stumbler/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG=	stumbler
BINDIR=	/usr/local/bin
LIBADD=	pcap ncursesw
CFLAGS=-g
MAN=

.include <bsd.prog.mk>
