# $FreeBSD: releng/12.0/tools/tools/wtap/wtap/Makefile 264400 2014-04-13 05:21:56Z imp $

BINDIR?=	/usr/local/bin
PROG=	wtap
SRC=	wtap.c
MAN=

CFLAGS+=	-I${.CURDIR}/../../../../sys/dev/wtap/

.include <bsd.prog.mk>
