# $FreeBSD: releng/12.0/sys/modules/geom/geom_mirror/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/geom/mirror

KMOD=	geom_mirror
SRCS=	g_mirror.c
SRCS+=	g_mirror_ctl.c

.include <bsd.kmod.mk>
