# $FreeBSD: releng/12.0/tools/tools/indent_wrapper/Makefile 291300 2015-11-25 13:26:42Z hselasky $
PREFIX?=        /usr/local
LOCALBASE?=     /usr/local
BINDIR=         ${PREFIX}/sbin
PROG=		indent_wrapper
MAN=
SRCS+=		indent_wrapper.c

.include <bsd.prog.mk>
