# $FreeBSD: releng/12.0/sys/modules/mac_veriexec_sha256/Makefile 335399 2018-06-20 00:41:30Z stevek $

.PATH: ${.CURDIR}/../../security/mac_veriexec
.PATH: ${.CURDIR}/../../crypto/sha2

KMOD=	mac_veriexec_sha256
SRCS=	mac_veriexec_sha256.c sha256c.c

.include <bsd.kmod.mk>

