# $FreeBSD: releng/12.0/stand/powerpc/Makefile 330250 2018-03-01 21:46:01Z kevans $

NO_OBJ=t

.include <bsd.init.mk>

SUBDIR.yes=		boot1.chrp ofw uboot
SUBDIR.${MK_FDT}+=	kboot

.include <bsd.subdir.mk>
