# $FreeBSD: releng/12.0/usr.sbin/ctm/ctm_smail/Makefile 314659 2017-03-04 11:38:03Z ngie $

.PATH: ${.CURDIR:H}/ctm_rmail

PROG=	ctm_smail
MAN=
SRCS=	ctm_smail.c error.c

CFLAGS+= -I${.CURDIR:H}/ctm_rmail

WARNS?=	2

.include <bsd.prog.mk>
