#	$OpenBSD: Makefile,v 1.1 1997/01/26 02:23:20 millert Exp $
# $FreeBSD: releng/12.0/sbin/fsirand/Makefile 328426 2018-01-26 00:58:32Z mckusick $

PACKAGE=runtime
PROG=	fsirand
MAN=	fsirand.8
LIBADD=	ufs
WARNS?=	3

.include <bsd.prog.mk>
