# $FreeBSD: releng/12.0/sys/modules/i2c/isl12xx/Makefile 323642 2017-09-16 16:09:05Z ian $

.PATH:		${SRCTOP}/sys/dev/iicbus
KMOD		= isl12xx
SRCS		= isl12xx.c bus_if.h clock_if.h device_if.h iicbus_if.h ofw_bus_if.h opt_platform.h

.include <bsd.kmod.mk>
