# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: releng/12.0/usr.sbin/amd/mk-amd-map/Makefile 305787 2016-09-14 01:47:01Z cy $

.PATH:	${SRCTOP}/contrib/amd/mk-amd-map

PROG=	mk-amd-map
MAN=	mk-amd-map.8

LIBADD=	amu

.include <bsd.prog.mk>
