#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/automountd 325400 2017-11-04 15:52:16Z trasz $
#

# PROVIDE: automountd
# REQUIRE: rpcbind ypset nfsclient FILESYSTEMS ldconfig
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="automountd"
desc="daemon handling autofs mount requests"
rcvar="autofs_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"
required_modules="autofs"

load_rc_config $name
run_rc_command "$1"
