#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/autounmountd 325400 2017-11-04 15:52:16Z trasz $
#

# PROVIDE: autounmountd
# REQUIRE: FILESYSTEMS
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="autounmountd"
desc="daemon unmounting automounted filesystems"
rcvar="autofs_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
