#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/bsnmpd 320618 2017-07-03 20:36:58Z kp $
#

# PROVIDE: bsnmpd
# REQUIRE: NETWORKING syslogd
# KEYWORD: nojailvnet shutdown

. /etc/rc.subr

name="bsnmpd"
desc="Simple and extensible SNMP daemon"
rcvar="bsnmpd_enable"
command="/usr/sbin/${name}"

load_rc_config $name
pidfile="${bsnmpd_pidfile:-/var/run/snmpd.pid}"
command_args="-p ${pidfile}"
run_rc_command "$1"
