#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/FILESYSTEMS 299839 2016-05-15 04:38:50Z ngie $
#

# PROVIDE: FILESYSTEMS
# REQUIRE: root mountcritlocal cleanvar

#	This is a dummy dependency, for services which require filesystems
#	to be mounted before starting.  It also serves as the default early /
#	late divider; after this point, rc.d directories are rescanned to
#	catch scripts from other filesystems than /.
