#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/hastd 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: hastd
# REQUIRE: NETWORKING syslogd
# BEFORE:  DAEMON
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="hastd"
desc="Highly Available Storage daemon"
rcvar="hastd_enable"
pidfile="/var/run/${name}.pid"
command="/sbin/${name}"
hastctl="/sbin/hastctl"
required_files="/etc/hast.conf"
stop_precmd="hastd_stop_precmd"
required_modules="geom_gate:g_gate"
extra_commands="reload"

hastd_stop_precmd()
{
	${hastctl} role init all
}

load_rc_config $name
run_rc_command "$1"
