#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/iscsid 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: iscsid
# REQUIRE: NETWORK
# BEFORE:  DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="iscsid"
desc="iSCSI initiator daemon"
rcvar="iscsid_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"
required_modules="iscsi"

load_rc_config $name
run_rc_command "$1"
