#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/keyserv 298514 2016-04-23 16:10:54Z lme $
#

# Start keyserv if we are running Secure RPC

# PROVIDE: keyserv
# REQUIRE: ypset
# BEFORE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="keyserv"
desc="Server for storing private encryption keys"
rcvar="keyserv_enable"
command="/usr/sbin/${name}"
start_precmd="keyserv_prestart"

keyserv_prestart()
{
	force_depend rpcbind || return 1
}

load_rc_config $name
run_rc_command "$1"
