#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/kfd 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: kfd
# REQUIRE: NETWORK
# KEYWORD: shutdown

. /etc/rc.subr

name=kfd
desc="Receive forwarded tickets"
rcvar=${name}_enable
start_precmd=${name}_start_precmd

kfd_start_precmd()
{

	command_args="$command_args -i &"
}

load_rc_config $name
run_rc_command "$1"
