#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/kldxref 333491 2018-05-11 14:43:21Z trasz $
#

# PROVIDE: kldxref
# REQUIRE: FILESYSTEMS
# BEFORE:  netif
# KEYWORD: nojail

. /etc/rc.subr

rcvar="kldxref_enable"
name="kldxref"
desc="Generate hints for the kernel loader"
stop_cmd=":"
start_cmd="kldxref_start"

kldxref_start() {
	if [ -n "$kldxref_module_path" ]; then
		MODULE_PATHS="$kldxref_module_path"
	else
		MODULE_PATHS=`sysctl -n kern.module_path`
	fi
	IFS=';'
	for MODULE_DIR in $MODULE_PATHS; do
		if checkyesno kldxref_clobber ||
		    [ ! -f "$MODULE_DIR/linker.hints" ] &&
		    [ `echo ${MODULE_DIR}/*.ko` != "${MODULE_DIR}/*.ko" ]; then
			echo "Building $MODULE_DIR/linker.hints"
			kldxref "$MODULE_DIR"
		fi
	done
}

load_rc_config $name
run_rc_command "$1"
