#!/bin/sh
#
# FreeBSD History: src/etc/rc.d/nfslocking,v 1.11 2004/10/07 13:55:26 mtm
# $FreeBSD: releng/12.0/libexec/rc/rc.d/lockd 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: lockd
# REQUIRE: nfsclient nfsd rpcbind statd
# BEFORE:  DAEMON
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="lockd"
desc="NFS file locking daemon"
rcvar=rpc_lockd_enable
command="/usr/sbin/rpc.${name}"
start_precmd='lockd_precmd'

# Make sure that we are either an NFS client or server, and that we get
# the correct flags from rc.conf(5).
#
lockd_precmd()
{
	force_depend rpcbind || return 1
	force_depend statd rpc_statd || return 1
	
	rc_flags=${rpc_lockd_flags}
}

load_rc_config $name
run_rc_command $1
