#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/LOGIN 278706 2015-02-13 20:52:23Z ngie $
#

# PROVIDE: LOGIN
# REQUIRE: DAEMON

#	This is a dummy dependency to ensure user services such as xdm,
#	inetd, cron and kerberos are started after everything else, in case
#	the administrator has increased the system security level and
#	wants to delay user logins until the system is (almost) fully
#	operational.
