#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/NETWORKING 299843 2016-05-15 05:45:54Z ngie $
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netwait netoptions routing ppp ipfw stf
# REQUIRE: defaultroute route6d resolv bridge
# REQUIRE: static_arp static_ndp

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
