#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/nfscbd 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: nfscbd
# REQUIRE: NETWORKING nfsuserd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="nfscbd"
desc="NFSv4 client side callback daemon"
rcvar="nfscbd_enable"
command="/usr/sbin/${name}"
sig_stop="USR1"

load_rc_config $name

run_rc_command "$1"
