#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/rarpd 320802 2017-07-08 09:28:31Z kp $
#

# PROVIDE: rarpd
# REQUIRE: DAEMON FILESYSTEMS
# BEFORE:  LOGIN
# KEYWORD: nojailvnet

. /etc/rc.subr

name="rarpd"
desc="Reverse ARP daemon"
rcvar="rarpd_enable"
command="/usr/sbin/${name}"
required_files="/etc/ethers"

load_rc_config $name
pidfile="${rarpd_pidfile:-/var/run/${name}.pid}"

run_rc_command "$1"
