#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/rtsold 320802 2017-07-08 09:28:31Z kp $
#

# PROVIDE: rtsold
# REQUIRE: netif
# BEFORE: NETWORKING
# KEYWORD: nojailvnet shutdown

. /etc/rc.subr

name="rtsold"
desc="Router solicitation daemon"
rcvar="rtsold_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
start_postcmd="rtsold_poststart"

rtsold_poststart()
{
	# wait for DAD
	sleep $(($(${SYSCTL_N} net.inet6.ip6.dad_count) + 1))
}

load_rc_config $name
run_rc_command "$1"
