#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/SERVERS 298844 2016-04-30 09:50:08Z ngie $
#

# PROVIDE: SERVERS
# REQUIRE: mountcritremote abi ldconfig savecore watchdogd

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
