#!/bin/sh
#
# $FreeBSD: releng/12.0/libexec/rc/rc.d/swaplate 307755 2016-10-21 21:55:50Z jilles $
#

# PROVIDE: swaplate
# REQUIRE: mountlate
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="swaplate"
desc="Setup late swap space"
start_cmd='/sbin/swapon -aLq'
stop_cmd='/sbin/swapoff -aLq'

load_rc_config swap
run_rc_command "$1"
