#	$FreeBSD: releng/12.0/sbin/ipf/Makefile 315223 2017-03-14 02:10:37Z cy $

SUBDIR=		libipf .WAIT
SUBDIR+=	ipf ipfs ipfstat ipmon ipnat ippool
# XXX Temporarily disconnected.
# SUBDIR+=	ipftest ipresend
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
