# $FreeBSD: releng/12.0/sys/modules/sound/driver/envy24ht/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/pci

KMOD=	snd_envy24ht
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	envy24ht.c

.include <bsd.kmod.mk>
