# $FreeBSD: releng/12.0/sys/modules/sound/driver/sb8/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/isa

KMOD=	snd_sb8
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h
SRCS+=	sb8.c

.include <bsd.kmod.mk>
