#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/12.0/usr.bin/rs/Makefile 326289 2017-11-27 20:01:58Z asomers $

.include <src.opts.mk>

PROG=	rs

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
