# $FreeBSD: releng/12.0/share/doc/legal/realtek/Makefile 314652 2017-03-04 11:26:40Z ngie $

FILES=		${SRCTOP}/sys/contrib/dev/rtwn/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal
FILESNAME=	realtek.LICENSE

.include <bsd.prog.mk>
