# $FreeBSD: releng/12.0/sys/modules/ata/atacard/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/dev/ata

KMOD=	atacard
SRCS=	ata-card.c
SRCS+=	ata_if.h bus_if.h card_if.h device_if.h pccarddevs.h

.include <bsd.kmod.mk>
