# $FreeBSD: releng/12.0/lib/libc/arm/string/Makefile.inc 314556 2017-03-02 17:05:52Z brooks $

MDSRCS+= \
	bcopy.S \
	bzero.S \
	ffs.S \
	memcmp.S \
	memcpy.S \
	memmove.S \
	memset.S \
	strcmp.S \
	strlen.S \
	strncmp.S
