# $FreeBSD: releng/12.0/sys/modules/acpi/acpi_rapidstart/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH:		${SRCTOP}/sys/dev/acpi_support

KMOD=		acpi_rapidstart
SRCS=		acpi_rapidstart.c opt_acpi.h device_if.h bus_if.h acpi_if.h

.include <bsd.kmod.mk>
