# $FreeBSD: releng/12.0/lib/geom/multipath/Makefile 314656 2017-03-04 11:33:01Z ngie $

PACKAGE=runtime
.PATH: ${.CURDIR:H:H}/misc

GEOM_CLASS=	multipath

CFLAGS+=  -I${SRCTOP}/sys

.include <bsd.lib.mk>
